#name: Build and Deploy
#on: [push]
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@master
#
#      - name: vuepress-deploy
#        uses: jenkey2011/vuepress-deploy@master
#        env:
#          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#          TARGET_REPO: waynehfut/dsa
#          TARGET_BRANCH: gh-pages
#          BUILD_SCRIPT: yarn && yarn docs:build
#          BUILD_DIR: docs/.vuepress/dist
#          CNAME: https://dsa.waynehfut.com

name: docs

on:
  # æ¯å½“ push åˆ° main åˆ†æ”¯æ—¶è§¦å‘éƒ¨ç½²
  push:
    branches: [ main ]
  # æ‰‹åŠ¨è§¦å‘éƒ¨ç½²
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # â€œæœ€è¿‘æ›´æ–°æ—¶é—´â€ ç­‰ git æ—¥å¿—ç›¸å…³ä¿¡æ¯ï¼Œéœ€è¦æ‹‰å–å…¨éƒ¨æäº¤è®°å½•
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # é€‰æ‹©è¦ä½¿ç”¨çš„ node ç‰ˆæœ¬
          node-version: 18
          # ç¼“å­˜ pnpm ä¾èµ–
          cache: 'yarn'

      - name: Install dependencies ğŸ“¦
        run: yarn install --frozen-lockfile

      # è¿è¡Œæ„å»ºè„šæœ¬
      - name: Build VuePress site
        run: yarn docs:build

      # æŸ¥çœ‹ workflow çš„æ–‡æ¡£æ¥è·å–æ›´å¤šä¿¡æ¯
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # éƒ¨ç½²åˆ° gh-pages åˆ†æ”¯
          target_branch: gh-pages
          # éƒ¨ç½²ç›®å½•ä¸º VuePress çš„é»˜è®¤è¾“å‡ºç›®å½•
          build_dir: docs/.vuepress/dist
          fqdn: dsa.waynehfut.com
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
